# arguments for dataset
dataset: MSDBrain
nclass: 4
crop_size: 128
img_root: data/Task01_BrainTumour/imagesTr
mask_root: data/Task01_BrainTumour/labelsTr

# arguments for training
optim: SGD
epochs: 100
batch_size: 1
lr: 0.001  # 4GPUs
lr_multi: 0.0
criterion:
  name: CrossEntropyAndDice
  kwargs:
    ignore_index: 255
    alpha: 1.0

eval_mode: sliding_window
sw_stride_ratio: 0.625
scheduler: 
  name: PolynomialLR
  kwargs:
    power: 0.9
lr_decay_per_epoch: False
lr_decay_per_step: True

# arguments for backbone
backbone:
  name: UNet3D
  kwargs:
    in_channels: 4
    base_channels: 64
    bilinear: True

# arguments for decode_head
decode_head:
  name: FCN3DHead
  kwargs:
    channels: 64
    num_convs: 0
    concat_input: False