# arguments for dataset
train_pd_root: data/new_pd_wip/v6/pd_paired
train_wip_root: data/new_pd_wip/v6/wip_registration
val_pd_root: data/new_pd_wip/v6/pd_paired
val_wip_root: data/new_pd_wip/v6/wip_registration

# arguments for training
optim: AdamW
epochs: 200
batch_size: 1
lr: 0.0002  # 4GPUs
crop_size: 128
scheduler: 
  name: CosineAnnealingLR
  kwargs:
    T_max: 1080
    eta_min: 0.0
    
lr_decay_per_epoch: false
lr_decay_per_step: true
model: {
  name: "unet3d",
  kwargs: {
    in_channels: 1,
    base_channels: 32,
    add_residual: true
  }
}

