# arguments for dataset
train_pd_root: data/new_pd_wip/v6/pd_paired
train_wip_root: data/new_pd_wip/v6/wip_registration
val_pd_root: data/new_pd_wip/v6/pd_paired
val_wip_root: data/new_pd_wip/v6/wip_registration

# arguments for training
optim: AdamW
epochs: 50
batch_size: 4
lr: 0.0002  # 1GPUs
crop_size: 128
scheduler: 
  name: CosineAnnealingLR
  kwargs:
    T_max: 5000
    eta_min: 0.0

norm_type: "sample_max"
quantile_clip: false

lr_decay_per_epoch: false
lr_decay_per_step: true
model: {
  name: "unet3d",
  kwargs: {
    in_channels: 1,
    base_channels: 64,
    add_residual: true
  }
}

